export const imageCandidates = ["photo.jpg", "photo.jpeg", "photo.png", "photo.webp"];

export const provinces = [
  { id: "65", slug: "xinjiang", zh: "新疆", en: "Xinjiang" },
  { id: "54", slug: "tibet", zh: "西藏", en: "Tibet" },
  { id: "63", slug: "qinghai", zh: "青海", en: "Qinghai" },
  { id: "62", slug: "gansu", zh: "甘肃", en: "Gansu" },
  { id: "15", slug: "inner-mongolia", zh: "内蒙古", en: "Inner Mongolia" },
  { id: "64", slug: "ningxia", zh: "宁夏", en: "Ningxia" },
  { id: "61", slug: "shaanxi", zh: "陕西", en: "Shaanxi" },
  { id: "14", slug: "shanxi", zh: "山西", en: "Shanxi" },
  { id: "13", slug: "hebei", zh: "河北", en: "Hebei" },
  { id: "11", slug: "beijing", zh: "北京", en: "Beijing" },
  { id: "12", slug: "tianjin", zh: "天津", en: "Tianjin" },
  { id: "21", slug: "liaoning", zh: "辽宁", en: "Liaoning" },
  { id: "22", slug: "jilin", zh: "吉林", en: "Jilin" },
  { id: "23", slug: "heilongjiang", zh: "黑龙江", en: "Heilongjiang" },
  { id: "37", slug: "shandong", zh: "山东", en: "Shandong" },
  { id: "41", slug: "henan", zh: "河南", en: "Henan" },
  { id: "32", slug: "jiangsu", zh: "江苏", en: "Jiangsu" },
  { id: "31", slug: "shanghai", zh: "上海", en: "Shanghai" },
  { id: "34", slug: "anhui", zh: "安徽", en: "Anhui" },
  { id: "42", slug: "hubei", zh: "湖北", en: "Hubei" },
  { id: "51", slug: "sichuan", zh: "四川", en: "Sichuan" },
  { id: "50", slug: "chongqing", zh: "重庆", en: "Chongqing" },
  { id: "33", slug: "zhejiang", zh: "浙江", en: "Zhejiang" },
  { id: "36", slug: "jiangxi", zh: "江西", en: "Jiangxi" },
  { id: "43", slug: "hunan", zh: "湖南", en: "Hunan" },
  { id: "52", slug: "guizhou", zh: "贵州", en: "Guizhou" },
  { id: "53", slug: "yunnan", zh: "云南", en: "Yunnan" },
  { id: "45", slug: "guangxi", zh: "广西", en: "Guangxi" },
  { id: "44", slug: "guangdong", zh: "广东", en: "Guangdong" },
  { id: "35", slug: "fujian", zh: "福建", en: "Fujian" },
  { id: "46", slug: "hainan", zh: "海南", en: "Hainan" },
  { id: "81", slug: "hong-kong", zh: "香港", en: "Hong Kong" },
  { id: "82", slug: "macau", zh: "澳门", en: "Macau" },
  { id: "71", slug: "taiwan", zh: "台湾", en: "Taiwan" }
];
